"""create candidate profiles table

Revision ID: 2bf94408b59b
Revises: b39a4a8777dc
Create Date: 2026-06-02 14:30:27.293615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bf94408b59b'
down_revision: Union[str, Sequence[str], None] = 'b39a4a8777dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cv_profile_id', sa.String(length=36), nullable=False),
    sa.Column('target_roles', sa.JSON(), nullable=False),
    sa.Column('core_skills', sa.JSON(), nullable=False),
    sa.Column('secondary_skills', sa.JSON(), nullable=False),
    sa.Column('seniority', sa.String(length=100), nullable=False),
    sa.Column('domains', sa.JSON(), nullable=False),
    sa.Column('experience_summary', sa.JSON(), nullable=False),
    sa.Column('location_preferences', sa.JSON(), nullable=False),
    sa.Column('work_arrangement_preferences', sa.JSON(), nullable=False),
    sa.Column('extraction_notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cv_profile_id'], ['cv_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_profiles_cv_profile_id'), 'candidate_profiles', ['cv_profile_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidate_profiles_cv_profile_id'), table_name='candidate_profiles')
    op.drop_table('candidate_profiles')
    # ### end Alembic commands ###
