"""create job requirements table

Revision ID: 2dba99af9183
Revises: 6dc941986ae8
Create Date: 2026-06-02 15:56:20.999567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dba99af9183'
down_revision: Union[str, Sequence[str], None] = '6dc941986ae8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_requirements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_listing_id', sa.String(length=36), nullable=False),
    sa.Column('required_skills', sa.JSON(), nullable=False),
    sa.Column('preferred_skills', sa.JSON(), nullable=False),
    sa.Column('responsibilities', sa.JSON(), nullable=False),
    sa.Column('seniority', sa.String(length=100), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('employment_type', sa.String(length=100), nullable=False),
    sa.Column('work_arrangement', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('salary_range', sa.String(length=255), nullable=False),
    sa.Column('application_deadline', sa.String(length=255), nullable=False),
    sa.Column('hard_requirements', sa.JSON(), nullable=False),
    sa.Column('nice_to_have', sa.JSON(), nullable=False),
    sa.Column('keywords_for_ats', sa.JSON(), nullable=False),
    sa.Column('extraction_notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_listing_id'], ['job_listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_requirements_job_listing_id'), 'job_requirements', ['job_listing_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_requirements_job_listing_id'), table_name='job_requirements')
    op.drop_table('job_requirements')
    # ### end Alembic commands ###
