"""create match scores table

Revision ID: a1c414507793
Revises: 2dba99af9183
Create Date: 2026-06-02 16:07:23.591102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1c414507793'
down_revision: Union[str, Sequence[str], None] = '2dba99af9183'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_scores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('candidate_profile_id', sa.String(length=36), nullable=False),
    sa.Column('job_requirement_id', sa.String(length=36), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('technical_skill_score', sa.Integer(), nullable=False),
    sa.Column('responsibility_score', sa.Integer(), nullable=False),
    sa.Column('seniority_score', sa.Integer(), nullable=False),
    sa.Column('domain_score', sa.Integer(), nullable=False),
    sa.Column('location_score', sa.Integer(), nullable=False),
    sa.Column('constraints_score', sa.Integer(), nullable=False),
    sa.Column('career_strategy_score', sa.Integer(), nullable=False),
    sa.Column('recommendation', sa.String(length=50), nullable=False),
    sa.Column('matched_skills', sa.JSON(), nullable=False),
    sa.Column('missing_required_skills', sa.JSON(), nullable=False),
    sa.Column('matched_preferred_skills', sa.JSON(), nullable=False),
    sa.Column('matched_responsibilities', sa.JSON(), nullable=False),
    sa.Column('gaps', sa.JSON(), nullable=False),
    sa.Column('reasoning_summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_requirement_id'], ['job_requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_scores_candidate_profile_id'), 'match_scores', ['candidate_profile_id'], unique=False)
    op.create_index(op.f('ix_match_scores_job_requirement_id'), 'match_scores', ['job_requirement_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_scores_job_requirement_id'), table_name='match_scores')
    op.drop_index(op.f('ix_match_scores_candidate_profile_id'), table_name='match_scores')
    op.drop_table('match_scores')
    # ### end Alembic commands ###
